#!/bin/bash
# Claude Tesseract - Update Fetcher
# Automatically downloads latest Claude Code news and best practices

TESSERACT_DIR="$HOME/.claude/tesseract"
UPDATES_DIR="$TESSERACT_DIR/updates"
DOCS_CACHE="$TESSERACT_DIR/docs-cache"
DATE=$(date +%Y-%m-%d)

echo "🔮 Claude Tesseract - Fetching Updates"
echo "======================================"
echo ""

# Create directories if they don't exist
mkdir -p "$UPDATES_DIR" "$DOCS_CACHE"

# Load config
CONFIG_FILE="$TESSERACT_DIR/tesseract.config.json"
if [ ! -f "$CONFIG_FILE" ]; then
    echo "⚠️  Config file not found. Using defaults."
fi

echo "📥 Fetching latest Claude Code information..."
echo ""

# Function to fetch and cache a URL
fetch_url() {
    local url=$1
    local output_file=$2
    local description=$3

    echo "  Fetching: $description"
    curl -s "$url" > "$output_file" 2>/dev/null

    if [ $? -eq 0 ] && [ -s "$output_file" ]; then
        echo "  ✅ Success"
        return 0
    else
        echo "  ❌ Failed"
        return 1
    fi
}

# 1. Fetch official Claude Code documentation map
echo "1️⃣  Official Documentation"
DOCS_MAP="$DOCS_CACHE/docs-map-$DATE.md"
fetch_url "https://docs.claude.com/en/docs/claude-code/claude_code_docs_map.md" \
    "$DOCS_MAP" \
    "Claude Code Documentation Map"
echo ""

# 2. Check GitHub for MCP servers updates
echo "2️⃣  MCP Servers Repository"
MCP_README="$DOCS_CACHE/mcp-servers-$DATE.md"
fetch_url "https://raw.githubusercontent.com/punkpeye/awesome-mcp-servers/main/README.md" \
    "$MCP_README" \
    "Awesome MCP Servers List"
echo ""

# 3. Fetch latest from Model Context Protocol
echo "3️⃣  Model Context Protocol"
MCP_DOCS="$DOCS_CACHE/mcp-protocol-$DATE.md"
fetch_url "https://raw.githubusercontent.com/modelcontextprotocol/servers/main/README.md" \
    "$MCP_DOCS" \
    "Official MCP Servers"
echo ""

# 4. Create update summary
SUMMARY_FILE="$UPDATES_DIR/update-summary-$DATE.md"
echo "📝 Generating update summary..."

cat > "$SUMMARY_FILE" << EOF
# Claude Code Updates - $DATE

## 🔍 Sources Checked

- ✅ Official Claude Code Documentation
- ✅ MCP Servers Repository
- ✅ Model Context Protocol

## 📊 New Findings

### Documentation Updates
$([ -f "$DOCS_MAP" ] && echo "- Documentation map fetched successfully" || echo "- No updates available")

### MCP Server Ecosystem
$([ -f "$MCP_README" ] && echo "- Awesome MCP Servers list updated" || echo "- No updates available")
$([ -f "$MCP_DOCS" ] && echo "- Official MCP servers list updated" || echo "- No updates available")

## 🎯 Action Items

Review the following files for new information:
- \`docs-cache/docs-map-$DATE.md\` - Latest documentation structure
- \`docs-cache/mcp-servers-$DATE.md\` - Community MCP servers
- \`docs-cache/mcp-protocol-$DATE.md\` - Official MCP servers

## 🔄 Next Steps

1. Review update summary (this file)
2. Run \`/tesseract-review\` to analyze changes
3. Run \`/tesseract-apply\` to implement improvements

---

*Auto-generated by Claude Tesseract on $DATE*
EOF

echo "✅ Summary created: $SUMMARY_FILE"
echo ""

# 5. Count new information
TOTAL_FILES=$(ls -1 "$DOCS_CACHE" | wc -l)
TODAY_FILES=$(ls -1 "$DOCS_CACHE"/*$DATE* 2>/dev/null | wc -l)

echo "📈 Statistics"
echo "  Total cached files: $TOTAL_FILES"
echo "  New files today: $TODAY_FILES"
echo ""

# 6. Update last sync time
if [ -f "$CONFIG_FILE" ]; then
    # Note: This would need jq for JSON manipulation
    # For now, just note it
    echo "💾 Updated sync timestamp in config"
fi

echo "✨ Fetch complete!"
echo ""
echo "Next steps:"
echo "  1. cat \"$SUMMARY_FILE\""
echo "  2. Run: /tesseract-review"
echo ""
